{% set name = "WildMagic" %}
{% set version = "5.14" %}
{% set version_major = "5" %}
{% set version_minor = "14" %}
{% set sha256 = "951330bca2328d537dac2459bf154845295b8c4576a0adca5ffbf31b5a778d80" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: http://www.geometrictools.com/Downloads/WildMagic{{ version_major }}p{{ version_minor }}.zip
  sha256: {{ sha256 }}

  patches:
    - wm5_path.patch

build:
  number: 0
  skip: True  # [win]
  binary_has_prefix_files:
    - lib/libWm5Applications.so.5.14

requirements:
  build:
    - toolchain

test:
  commands:
    - test -f $PREFIX/include/libwildmagic/Wm5Visual.h  # [unix]
    - test -e $PREFIX/lib/libWm5Core.so  # [unix]

about:
  home: https://www.geometrictools.com/Downloads/Downloads.html
  license: BSL-1.0
  license_file: WildMagic5/License/LICENSE_1_0.txt
  summary: 'Library for computer graphics, mathematics, physics, numerics and image analysis'

  description: |
     The WildMagic5 libraries are meant to help developers perform
     computing tasks in the following specialties:

     - computer graphics
     - mathematics
     - physics
     - numerical methods
     - image analysis.

     The source code is divided in such a manner that is provides these
     libraries:

     - The LibCore library contains some basic support that applications
       need. Some of this support is for convenience during development;
     - The LibMathematics library;
     - The LibGraphics library;
     - The LibPhysics library;
     - The LibApplications library.

extra:
  recipe-maintainers:
    - aseyboldt
