{% set name = "xsd" %}
{% set version = "4.0.0" %}
{% set sha256 = "eca52a9c8f52cdbe2ae4e364e4a909503493a0d51ea388fc6c9734565a859817" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://www.codesynthesis.com/download/{{ name }}/4.0/{{ name }}-{{ version }}+dep.tar.bz2
  sha256: {{ sha256 }}

  patches:
    # The patches are used in the homebrew formula, too.
    # https://github.com/Homebrew/homebrew-core/blob/7a4dabfc1a2a/Formula/xsd.rb

    # clang >=4.0.0 requires an explicit `#include <iostream>`
    # http://www.codesynthesis.com/pipermail/xsd-users/2015-February/004522.html
    - osx-build.patch
    # BSD find does not support `-printf`
    # see http://codesynthesis.com/pipermail/xsd-users/2015-June/004638.html
    - osx-test.patch

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - toolchain
    - pkg-config
    - xerces-c 3.1.*
    - python
  run:
    - pkg-config
    - xerces-c 3.1.*

test:
  commands:
    - xsd version > /dev/null

about:
  home: http://www.codesynthesis.com/projects/xsd/
  license: GPL2
  license_file: xsd/GPLv2
  summary: 'An open-source, cross-platform W3C XML Schema to C++ data binding compiler'

extra:
  recipe-maintainers:
    - aseyboldt
